/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

// import * as THREE from 'three'
import React, { useRef } from 'react';
import { useLoader } from 'react-three-fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useLoader(GLTFLoader, '/first.gltf');
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={nodes.Cube.material} geometry={nodes.Cube.geometry} position={[0, 1, 0]} />
      <mesh material={nodes.Cube002.material} geometry={nodes.Cube002.geometry} position={[-4, 1, 0]} />
      <mesh material={materials['Material.002']} geometry={nodes.Cube001.geometry} position={[4, 1, 0]} />
    </group>
  );
}
