/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, '/lego.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <group name="Walls">
          <mesh
            material={materials.Material}
            geometry={nodes.Cube.geometry}
            name="Cube"
            position={[0, 1, 0]}
            userData={{ name: 'Cube' }}
          />
        </group>
      </scene>
    </group>
  )
}
