import { GeoJsonPolygon, RectJson }  from '../geom/types';
import { Poly }  from '../geom';

declare namespace Geomorph {

  /** Generated by script `svg-meta`. */
  export type SvgJson = Record<string, ParsedSymbol<GeoJsonPolygon>>;

  export type ParsedSvgJson = Record<string, ParsedSymbol<Poly>>;

  export interface ParsedSymbol<T> {
    key: string;
    /** Only exists for hull symbols */
    hullRect?: RectJson;
    pngRect: RectJson;
    svgInnerText?: string;
    doors: T[];
    /** Only exists for hull symbols; assumed connected. */
    hull: T[];
    irisValves: T[];
    labels: T[];
    obstacles: T[];
    walls: T[];
  }

  export interface SymbolLayout {
    /**
     * Corresponds to basename of original PNG,
     * e.g. `g-301--bridge` where public/debug/g-301--bridge.png exists.
     */
    key: string;
    id: number;
    items: SymbolLayoutItem[];
  }

  export interface SymbolLayoutItem {
    symbol: string;
    hull?: boolean;
    transform?: [number, number, number, number, number, number];
    tags?: string[];
  }
}

export = Geomorph;
