import { GeoJsonPolygon, RectJson }  from '../geom/types';

/**
 * @typedef {Record<string, ParsedSymbol<GeoJsonPolygon>>} SvgJson
 * Generated by script `svg-meta`.
 */

/**
 * @template T
 * @typedef ParsedSymbol @type {object}
 * @property {string} key Symbol name.
 * @property {T[]} doors
 * @property {T[]} hull Assumed connected, if exists.
 * @property {T[]} irisValves
 * @property {T[]} labels
 * @property {T[]} obstacles
 * @property {RectJson} pngRect
 * @property {string | undefined} svgInnerText
 * @property {T[]} walls
 */

/**
 * @typedef SymbolLayout @type {object}
 * @property {string} key Corresponds to basename of original PNG,
 * e.g. `g-301--bridge` where public/debug/g-301--bridge.png exists.
 * @property {number} id
 * @property {SymbolLayoutItem[]} items
 */

/**
 * @typedef SymbolLayoutItem @type {object}
 * @property {string} symbol
 * @property {boolean} [hull]
 * @property {number[]} [transform]
 * @property {string[]} [tags]
 */
