
declare namespace NPC {
  
  import { Subject } from 'rxjs';
  
  export interface NPCsProps {
    disabled?: boolean;
    gmGraph: Graph.GmGraph;
    panZoomApi: PanZoom.CssExtApi;
    doorsApi: NPC.DoorsApi;
    wireKey: string;
  }

  type PointerEvent = {
    point: Geom.VectJson;
  } & (
    | { key: 'pointerdown' }
    | { key: 'pointerup' }
    | { key: 'pointerleave' }
    | { key: 'pointermove' }
  );

  type NpcEvent = (
    | { key: 'spawn'; npcKey: string; at: Geom.VectJson; }
    | { key: 'move-req'; npcKey: string; path: Geom.VectJson[]; }
    | {
        key: 'move-res';
        req: (NpcEvent & { key: 'move-req' });
        res: any // TODO provide anim
      }
    | { key: 'nav-req'; npcKey: string; dst: Geom.VectJson; }
    | {
        key: 'nav-res';
        req: (NpcEvent & { key: 'nav-req' });
        res: null | { paths: Geom.Vect[][]; edges: NPC.NavGmTransition[] };
      }
    | { key: 'debug-path'; path: Geom.VectJson[]; pathName: string }
  );

  export interface NPC {
    /** User specified e.g. andros */
    key: string;
    /** Autogenerated e.g. andros-3 */
    uid: string;
    def: NPCDef;
    spriteSheetState: 'idle' | 'walk';
    el: {
      root: HTMLDivElement;
      body: HTMLDivElement;
    };
    anim: {
      root: Animation;
      body: Animation;
    };
    /** Radians */
    getAngle(): number;
    getPosition(): Geom.Vect;
  }

  export type NavWire = import('rxjs').Subject<NPC.NavMessage>;

  export type NavMessage = (
    | DoorMessage
  );

  export interface DoorMessage {
    key: 'opened-door' | 'closed-door';
    gmIndex: number;
    index: number;
  }

  export interface DoorsProps {
    gms: Geomorph.GeomorphDataInstance[];
    gmGraph: Graph.GmGraph;
    wire: NavWire;
    initOpen: { [gmId: number]: number[] }
    onLoad: (api: DoorsApi) => void;
  }

  export interface DoorsApi {
    getVisible(gmIndex: number): number[];
    getClosed(gmIndex: number): number[];
    /** Get ids of open doors */
    getOpen(gmIndex: number): number[];
    get ready(): boolean;
    setVisible(gmIndex: number, doorIds: number[]): void ;
  }

  export interface UseGeomorphsNav {
    pfs: NPC.PfData[];
  }

  export interface PfData {
    graph: Graph.FloorGraph;
  }

  export interface NavGmTransition {
    src: {
      gmId: number;
      hullDoorId: number;
      /** World coords */
      exit: Geom.Vect;
    };
    dst: {
      gmId: number;
      hullDoorId: number;
      /** World coords */
      entry: Geom.Vect;
    };
  }

  export interface NavRoomTransition {
    doorId: number;
    srcRoomId: number;
    dstRoomId: number;
    entry: Geom.Vect;
    exit: Geom.Vect;
  }

  // OLD BELOW
  ////////////

  export interface NPCsPropsOld {
    wireKey: string;
    gmGraph: Graph.GmGraph;
    disabled?: boolean;
    onLoad: ((api: NPC.NPCsApi) => void);
  }

  export interface NPCsApi {
    apis: NPCApi[];
    root: HTMLDivElement;
    npcRef: React.RefCallback<HTMLDivElement>;
    rootRef: React.RefCallback<HTMLDivElement>;
    // spawn(defs: NPCDef[]): void;
  }

  export interface NPCApi {
    key: string;
    def: NPCDef;
    animState: 'idle' | 'walk';
    el: {
      root: HTMLDivElement;
    };
  }

  export interface NPCDef {
    key: string;
    position: Geom.VectJson;
    angle: number;
    // zoneKey: string;
    // /** Initially paused? */
    // paused: boolean;
    // /** Initial position */
    // src: Geom.VectJson;
    // /** Initial target */
    // dst: Geom.VectJson;
    // /** Initial angle */
  }

  export type AnimState = (
    | 'idle'
    | 'walk'
  );

}
